import { useMemo, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

type Client = { id:string; name:string; service:string; location:string; schedule:string; continuity:number; status:"Active"|"On hold" };
const seed: Client[] = [
  { id:"c1", name:"Mary Thompson", service:"Personal Care", location:"Dracut, MA", schedule:"Mon–Fri mornings", continuity:92, status:"Active" },
  { id:"c2", name:"Robert Davis", service:"Companionship", location:"Lowell, MA", schedule:"Tue/Thu/Sat evenings", continuity:88, status:"Active" },
  { id:"c3", name:"Alice Green", service:"Respite Care", location:"Chelmsford, MA", schedule:"As needed", continuity:71, status:"On hold" },
];
export default function ClientsScreen(){
 const [clients,setClients]=useState(seed); const [q,setQ]=useState(""); const [show,setShow]=useState(false); const [draft,setDraft]=useState({name:"",service:"",location:"",schedule:""});
 const visible=useMemo(()=>clients.filter(c=>`${c.name} ${c.service} ${c.location}`.toLowerCase().includes(q.toLowerCase())),[clients,q]);
 const add=()=>{if(!draft.name.trim()||!draft.service.trim())return Alert.alert("Missing information","Add client name and service.");setClients([{id:String(Date.now()),...draft,continuity:100,status:"Active"},...clients]);setDraft({name:"",service:"",location:"",schedule:""});setShow(false);};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}>
  <View style={s.header}><View><Text style={s.eye}>ELITE BRIDGE EMPLOYER</Text><Text style={s.title}>Clients</Text></View><TouchableOpacity style={s.primary} onPress={()=>setShow(!show)}><Text style={s.primaryText}>{show?"Cancel":"+ Add"}</Text></TouchableOpacity></View>
  <Text style={s.sub}>Service plans with a continuity lens — not just a contact list.</Text>
  <TextInput value={q} onChangeText={setQ} placeholder="Search clients or locations" placeholderTextColor="#98A2B3" style={s.input}/>
  {show&&<View style={s.card}><Text style={s.cardTitle}>New client</Text>{(["name","service","location","schedule"] as const).map(f=><TextInput key={f} value={draft[f]} onChangeText={v=>setDraft({...draft,[f]:v})} placeholder={f[0].toUpperCase()+f.slice(1)} placeholderTextColor="#98A2B3" style={s.input}/>) }<TouchableOpacity style={s.primaryWide} onPress={add}><Text style={s.primaryText}>Create client</Text></TouchableOpacity></View>}
  {visible.map(c=><View key={c.id} style={s.card}><View style={s.row}><View style={{flex:1}}><Text style={s.cardTitle}>{c.name}</Text><Text style={s.meta}>{c.service} · {c.location}</Text><Text style={s.meta}>{c.schedule}</Text></View><View style={s.score}><Text style={s.scoreValue}>{c.continuity}</Text><Text style={s.scoreLabel}>Continuity</Text></View></View><View style={s.insight}><Text style={s.insightTitle}>AI continuity insight</Text><Text style={s.insightText}>{c.continuity>=85?"Keep the current caregiver rotation where possible; this relationship is stable.":"Caregiver changes have increased. Favor familiar staff on the next assignments."}</Text></View></View>)}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F7F9F8"},content:{padding:18,paddingBottom:90},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},eye:{fontSize:10,fontWeight:"900",letterSpacing:1.2,color:"#C58A24"},title:{fontSize:30,fontWeight:"900",color:"#101828",marginTop:4},sub:{color:"#667085",marginTop:6,marginBottom:16},primary:{backgroundColor:"#0A4A35",paddingHorizontal:14,paddingVertical:10,borderRadius:10},primaryWide:{backgroundColor:"#0A4A35",padding:13,borderRadius:10,alignItems:"center",marginTop:4},primaryText:{color:"white",fontWeight:"900"},input:{borderWidth:1,borderColor:"#D0D5DD",backgroundColor:"white",borderRadius:10,padding:12,marginBottom:11,color:"#101828"},card:{backgroundColor:"white",borderWidth:1,borderColor:"#E4E7EC",borderRadius:16,padding:15,marginBottom:12},cardTitle:{fontSize:17,fontWeight:"900",color:"#101828"},row:{flexDirection:"row",gap:12},meta:{fontSize:12,color:"#667085",marginTop:4},score:{backgroundColor:"#ECF6F1",borderRadius:12,padding:10,alignItems:"center",minWidth:72},scoreValue:{fontSize:22,fontWeight:"900",color:"#0A4A35"},scoreLabel:{fontSize:9,fontWeight:"800",color:"#667085"},insight:{marginTop:13,padding:12,borderRadius:12,backgroundColor:"#F9FAFB"},insightTitle:{fontSize:11,fontWeight:"900",color:"#C58A24"},insightText:{fontSize:12,lineHeight:18,color:"#475467",marginTop:4}});
