import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";

type Entry={id:string;worker:string;client:string;date:string;hours:number;flag?:string;status:"Pending"|"Approved"};
const seed:Entry[]=[
{id:"t1",worker:"Sarah Johnson",client:"Robert Davis",date:"Aug 5",hours:5,status:"Pending"},
{id:"t2",worker:"Michael Brown",client:"Mary Thompson",date:"Aug 5",hours:8.5,flag:"Clock-out was 19 minutes outside expected location",status:"Pending"},
{id:"t3",worker:"Emily Rodriguez",client:"Alice Green",date:"Aug 4",hours:4,status:"Approved"},
];
export default function TimesheetsScreen(){const router=useRouter();const[entries,setEntries]=useState(seed);const approve=(id:string)=>{setEntries(entries.map(e=>e.id===id?{...e,status:"Approved"}:e));Alert.alert("Timesheet approved","The entry is ready for payroll export.")};return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.header}><TouchableOpacity onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></TouchableOpacity></View><Text style={s.eye}>ELITE BRIDGE EMPLOYER</Text><Text style={s.title}>Timesheets</Text><Text style={s.sub}>Review hours with AI-assisted exception flags before payroll.</Text>
{entries.map(e=><View key={e.id} style={s.card}><View style={s.row}><View style={{flex:1}}><Text style={s.name}>{e.worker}</Text><Text style={s.meta}>{e.client} · {e.date} · {e.hours} hrs</Text></View><Text style={[s.status,e.status==="Approved"?s.good:s.pending]}>{e.status}</Text></View>{e.flag&&<View style={s.flag}><Text style={s.flagTitle}>AI exception flag</Text><Text style={s.flagText}>{e.flag}</Text></View>}{e.status==="Pending"&&<View style={s.actions}><TouchableOpacity style={s.secondary} onPress={()=>Alert.alert("Correction requested","The worker will be asked to review this entry.")}><Text style={s.secondaryText}>Request correction</Text></TouchableOpacity><TouchableOpacity style={s.primary} onPress={()=>approve(e.id)}><Text style={s.primaryText}>Approve</Text></TouchableOpacity></View>}</View>)}
</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F7F9F8"},content:{padding:18,paddingBottom:90},header:{marginBottom:8},back:{color:"#0A4A35",fontWeight:"900",fontSize:16},eye:{fontSize:10,fontWeight:"900",letterSpacing:1.2,color:"#C58A24"},title:{fontSize:30,fontWeight:"900",color:"#101828",marginTop:4},sub:{color:"#667085",marginTop:6,marginBottom:16},card:{backgroundColor:"white",borderWidth:1,borderColor:"#E4E7EC",borderRadius:16,padding:15,marginBottom:12},row:{flexDirection:"row",gap:12},name:{fontSize:17,fontWeight:"900",color:"#101828"},meta:{fontSize:12,color:"#667085",marginTop:4},status:{fontSize:10,fontWeight:"900",paddingHorizontal:9,paddingVertical:6,borderRadius:999,overflow:"hidden"},good:{color:"#067647",backgroundColor:"#ECFDF3"},pending:{color:"#B54708",backgroundColor:"#FFFAEB"},flag:{marginTop:12,backgroundColor:"#FEF3F2",borderRadius:11,padding:11},flagTitle:{color:"#B42318",fontSize:10,fontWeight:"900",letterSpacing:.7},flagText:{color:"#475467",fontSize:12,lineHeight:18,marginTop:4},actions:{flexDirection:"row",gap:8,marginTop:12},secondary:{flex:1,backgroundColor:"#F2F4F7",padding:11,borderRadius:10,alignItems:"center"},secondaryText:{color:"#344054",fontWeight:"900",fontSize:12},primary:{flex:1,backgroundColor:"#0A4A35",padding:11,borderRadius:10,alignItems:"center"},primaryText:{color:"white",fontWeight:"900",fontSize:12}});
