import { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Alert, RefreshControl, ScrollView, Share, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect, useRouter } from "expo-router";
import Ionicons from "@expo/vector-icons/Ionicons";

import { approveEmployerTimesheet, EmployerTimesheet, getEmployerTimesheets, getStoredEmployer, requestTimesheetCorrection } from "../lib/api";
import { colors } from "../lib/theme";
import { EmployerTabBar } from "../components/employer-tab-bar";

type Filter = "pending" | "all" | "approved";

function label(status: EmployerTimesheet["status"]) {
  if (status === "in_progress") return "Clocked in";
  if (status === "submitted") return "Ready to review";
  if (status === "approved") return "Approved";
  return "Correction requested";
}

function formatDate(value?: string | null) {
  return value ? new Date(value).toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }) : "In progress";
}

function buildTimesheetDocument(item: EmployerTimesheet) {
  return [
    "ELITE BRIDGE TIMESHEET",
    `Timesheet #${item.id}`,
    "",
    `Employee: ${item.caregiverName || "Caregiver"}`,
    `Email: ${item.caregiverEmail || "Not provided"}`,
    `Shift: ${item.shiftTitle || item.serviceType || "Care shift"}`,
    `Scheduled: ${formatDate(item.scheduledStart)} – ${formatDate(item.scheduledEnd)}`,
    `Clock in: ${formatDate(item.clockInAt)}`,
    `Clock out: ${formatDate(item.clockOutAt)}`,
    `Unpaid breaks: ${item.breaks.length}`,
    `Approved hours: ${item.workedHours.toFixed(2)}`,
    `Hourly rate: $${item.hourlyRate.toFixed(2)}`,
    `Gross amount: $${item.grossAmount.toFixed(2)}`,
    `Status: ${label(item.status)}`,
    `Service notes: ${item.notes || "None"}`,
    item.approvedAt ? `Approved: ${formatDate(item.approvedAt)}` : "",
    "",
    "Generated by Elite Bridge Employer",
  ].filter(Boolean).join("\n");
}

export default function TimeScreen() {
  const router = useRouter();
  const [timesheets, setTimesheets] = useState<EmployerTimesheet[]>([]);
  const [filter, setFilter] = useState<Filter>("pending");
  const [correctionNotes, setCorrectionNotes] = useState<Record<number, string>>({});
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [busyId, setBusyId] = useState<number | null>(null);

  const load = useCallback(async (refresh = false) => {
    refresh ? setRefreshing(true) : setLoading(true);
    try {
      if (!await getStoredEmployer()) return router.replace("/sign-in");
      setTimesheets(await getEmployerTimesheets());
    } catch (error) {
      Alert.alert("Unable to load timesheets", error instanceof Error ? error.message : "Please try again.");
    } finally { setLoading(false); setRefreshing(false); }
  }, [router]);

  useFocusEffect(useCallback(() => { void load(); }, [load]));

  const visible = useMemo(() => timesheets.filter((item) => filter === "all" || (filter === "pending" ? item.status === "submitted" : item.status === "approved")), [filter, timesheets]);
  const activeCount = timesheets.filter((item) => item.status === "in_progress").length;
  const pendingCount = timesheets.filter((item) => item.status === "submitted").length;
  const approvedHours = timesheets.filter((item) => item.status === "approved").reduce((sum, item) => sum + item.workedHours, 0);
  const approvedGross = timesheets.filter((item) => item.status === "approved").reduce((sum, item) => sum + item.grossAmount, 0);

  const approve = async (item: EmployerTimesheet) => {
    setBusyId(item.id);
    try { await approveEmployerTimesheet(item.id); await load(true); Alert.alert("Timesheet approved", "The caregiver was notified."); }
    catch (error) { Alert.alert("Unable to approve", error instanceof Error ? error.message : "Please try again."); }
    finally { setBusyId(null); }
  };

  const requestCorrection = async (item: EmployerTimesheet) => {
    const note = correctionNotes[item.id]?.trim();
    if (!note) return Alert.alert("Correction note required", "Explain what the caregiver should correct.");
    setBusyId(item.id);
    try { await requestTimesheetCorrection(item.id, note); setCorrectionNotes((current) => ({ ...current, [item.id]: "" })); await load(true); Alert.alert("Correction requested", "The caregiver was notified."); }
    catch (error) { Alert.alert("Unable to request correction", error instanceof Error ? error.message : "Please try again."); }
    finally { setBusyId(null); }
  };

  const generate = async (item: EmployerTimesheet) => {
    await Share.share({ title: `Elite Bridge Timesheet ${item.id}`, message: buildTimesheetDocument(item) });
  };

  return <SafeAreaView edges={["bottom"]} style={styles.safe}><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.green} />}>
    <View style={styles.hero}><View style={{ flex: 1 }}><Text style={styles.eyebrow}>WORKFORCE OPERATIONS</Text><Text style={styles.heroTitle}>Timesheets</Text><Text style={styles.heroBody}>Review clocked shifts, approve hours, request corrections and generate a payroll-ready record.</Text></View><View style={styles.heroIcon}><Ionicons name="document-text" size={28} color="#FFFFFF" /></View></View>

    <View style={styles.stats}>
      <View style={styles.stat}><Text style={styles.statValue}>{activeCount}</Text><Text style={styles.statLabel}>Clocked in</Text></View>
      <View style={styles.stat}><Text style={styles.statValue}>{pendingCount}</Text><Text style={styles.statLabel}>To review</Text></View>
      <View style={styles.stat}><Text style={styles.statValue}>{approvedHours.toFixed(1)}</Text><Text style={styles.statLabel}>Approved hrs</Text></View>
    </View>
    <View style={styles.payroll}><View><Text style={styles.payrollLabel}>APPROVED LABOR</Text><Text style={styles.payrollValue}>${approvedGross.toFixed(2)}</Text></View><Ionicons name="checkmark-circle" size={30} color={colors.green} /></View>

    <View style={styles.filters}>{(["pending", "all", "approved"] as Filter[]).map((value) => <TouchableOpacity key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value && styles.filterActive]}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{value === "pending" ? "To review" : value[0].toUpperCase() + value.slice(1)}</Text></TouchableOpacity>)}</View>
    {loading ? <ActivityIndicator size="large" color={colors.green} style={styles.loader} /> : null}
    {!loading && visible.length === 0 ? <View style={styles.empty}><Ionicons name="document-text-outline" size={38} color={colors.green} /><Text style={styles.emptyTitle}>{filter === "pending" ? "No timesheets awaiting review" : "No timesheets in this view"}</Text><Text style={styles.emptyBody}>When a caregiver clocks out of an assigned shift, the completed record appears here automatically.</Text></View> : null}

    {visible.map((item) => <View key={item.id} style={styles.card}>
      <View style={styles.cardTop}><View style={{ flex: 1 }}><Text style={styles.name}>{item.caregiverName || "Caregiver"}</Text><Text style={styles.shift}>{item.shiftTitle || item.serviceType || "Care shift"}</Text><Text style={styles.date}>{formatDate(item.clockInAt)} – {formatDate(item.clockOutAt)}</Text></View><View style={[styles.badge, item.status === "approved" ? styles.approvedBadge : item.status === "correction_requested" ? styles.correctionBadge : styles.pendingBadge]}><Text style={styles.badgeText}>{label(item.status)}</Text></View></View>
      <View style={styles.hoursRow}><View><Text style={styles.metricLabel}>WORKED</Text><Text style={styles.metricValue}>{item.workedHours.toFixed(2)} hrs</Text></View><View><Text style={styles.metricLabel}>RATE</Text><Text style={styles.metricValue}>${item.hourlyRate.toFixed(2)}/hr</Text></View><View><Text style={styles.metricLabel}>GROSS</Text><Text style={styles.metricValue}>${item.grossAmount.toFixed(2)}</Text></View></View>
      {item.notes ? <View style={styles.notes}><Text style={styles.notesLabel}>SERVICE NOTES</Text><Text style={styles.notesText}>{item.notes}</Text></View> : null}
      {item.status === "submitted" ? <><TextInput value={correctionNotes[item.id] || ""} onChangeText={(value) => setCorrectionNotes((current) => ({ ...current, [item.id]: value }))} placeholder="Correction note (only if needed)" placeholderTextColor={colors.muted} multiline style={styles.input} /><View style={styles.actions}><TouchableOpacity disabled={busyId === item.id} onPress={() => void requestCorrection(item)} style={styles.outlineButton}><Text style={styles.outlineText}>Request correction</Text></TouchableOpacity><TouchableOpacity disabled={busyId === item.id} onPress={() => void approve(item)} style={styles.approveButton}>{busyId === item.id ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.approveText}>Approve hours</Text>}</TouchableOpacity></View></> : null}
      {item.employerNote ? <View style={styles.correctionNote}><Text style={styles.correctionLabel}>CORRECTION REQUEST</Text><Text style={styles.correctionText}>{item.employerNote}</Text></View> : null}
      <TouchableOpacity onPress={() => void generate(item)} style={styles.generateButton}><Ionicons name="share-outline" size={18} color={colors.green} /><Text style={styles.generateText}>Generate & share timesheet</Text></TouchableOpacity>
    </View>)}
  </ScrollView><EmployerTabBar /></SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background }, content: { padding: 19, paddingBottom: 42 }, hero: { flexDirection: "row", alignItems: "center", gap: 14, padding: 18, borderRadius: 20, backgroundColor: colors.greenDark }, eyebrow: { color: colors.gold, fontSize: 9, fontWeight: "900", letterSpacing: 1.3 }, heroTitle: { color: "#FFFFFF", fontSize: 27, fontWeight: "900", marginTop: 5 }, heroBody: { color: "#D6E7DE", fontSize: 12, lineHeight: 18, marginTop: 6 }, heroIcon: { width: 54, height: 54, borderRadius: 18, backgroundColor: "rgba(255,255,255,0.14)", alignItems: "center", justifyContent: "center" }, stats: { flexDirection: "row", gap: 8, marginTop: 12 }, stat: { flex: 1, backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: 14, padding: 12 }, statValue: { color: colors.ink, fontSize: 21, fontWeight: "900" }, statLabel: { color: colors.muted, fontSize: 9, fontWeight: "800", marginTop: 3 }, payroll: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 9, padding: 14, borderRadius: 14, backgroundColor: colors.greenSoft }, payrollLabel: { color: colors.green, fontSize: 9, fontWeight: "900", letterSpacing: 1 }, payrollValue: { color: colors.greenDark, fontSize: 23, fontWeight: "900", marginTop: 3 }, filters: { flexDirection: "row", gap: 8, marginVertical: 18 }, filter: { flex: 1, alignItems: "center", paddingVertical: 10, borderRadius: 999, backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1 }, filterActive: { backgroundColor: colors.green, borderColor: colors.green }, filterText: { color: colors.muted, fontSize: 11, fontWeight: "900" }, filterTextActive: { color: "#FFFFFF" }, loader: { marginTop: 55 }, empty: { alignItems: "center", backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: 18, padding: 30 }, emptyTitle: { color: colors.ink, fontSize: 17, fontWeight: "900", marginTop: 10, textAlign: "center" }, emptyBody: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 6, textAlign: "center" }, card: { backgroundColor: colors.card, borderColor: colors.border, borderWidth: 1, borderRadius: 18, padding: 15, marginBottom: 11 }, cardTop: { flexDirection: "row", gap: 10 }, name: { color: colors.ink, fontSize: 16, fontWeight: "900" }, shift: { color: colors.green, fontSize: 12, fontWeight: "800", marginTop: 4 }, date: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 4 }, badge: { alignSelf: "flex-start", borderRadius: 999, paddingHorizontal: 9, paddingVertical: 6 }, approvedBadge: { backgroundColor: colors.greenSoft }, pendingBadge: { backgroundColor: colors.warningSoft }, correctionBadge: { backgroundColor: "#FEE4E2" }, badgeText: { color: colors.ink, fontSize: 9, fontWeight: "900" }, hoursRow: { flexDirection: "row", justifyContent: "space-between", borderTopColor: colors.border, borderTopWidth: 1, marginTop: 13, paddingTop: 12 }, metricLabel: { color: colors.muted, fontSize: 8, fontWeight: "900", letterSpacing: 0.7 }, metricValue: { color: colors.ink, fontSize: 14, fontWeight: "900", marginTop: 3 }, notes: { backgroundColor: colors.background, borderRadius: 10, padding: 10, marginTop: 11 }, notesLabel: { color: colors.muted, fontSize: 8, fontWeight: "900" }, notesText: { color: colors.ink, fontSize: 11, lineHeight: 17, marginTop: 4 }, input: { minHeight: 65, borderColor: colors.border, borderWidth: 1, borderRadius: 11, color: colors.ink, padding: 10, marginTop: 11, textAlignVertical: "top" }, actions: { flexDirection: "row", gap: 8, marginTop: 9 }, outlineButton: { flex: 1, minHeight: 45, alignItems: "center", justifyContent: "center", borderColor: "#B42318", borderWidth: 1, borderRadius: 11 }, outlineText: { color: "#B42318", fontSize: 11, fontWeight: "900" }, approveButton: { flex: 1, minHeight: 45, alignItems: "center", justifyContent: "center", backgroundColor: colors.green, borderRadius: 11 }, approveText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, correctionNote: { backgroundColor: "#FFF5F4", borderRadius: 10, padding: 10, marginTop: 10 }, correctionLabel: { color: "#B42318", fontSize: 8, fontWeight: "900" }, correctionText: { color: "#7A271A", fontSize: 11, lineHeight: 17, marginTop: 4 }, generateButton: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, minHeight: 44, borderRadius: 11, backgroundColor: colors.greenSoft, marginTop: 10 }, generateText: { color: colors.green, fontSize: 12, fontWeight: "900" },
});
