import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useRouter } from "expo-router";

type Worker={id:string;name:string;role:string;hours:number;reliability:number;credentials:string;status:"Active"|"Needs review"};
const seed:Worker[]=[
{id:"w1",name:"Sarah Johnson",role:"Caregiver",hours:31,reliability:97,credentials:"CPR · First Aid",status:"Active"},
{id:"w2",name:"Michael Brown",role:"Companion",hours:37,reliability:94,credentials:"CPR",status:"Active"},
{id:"w3",name:"Emily Rodriguez",role:"Home Health Aide",hours:22,reliability:89,credentials:"CPR expires in 8 days",status:"Needs review"},
{id:"w4",name:"James Wilson",role:"Caregiver",hours:18,reliability:92,credentials:"Background check pending",status:"Needs review"},
];
export default function WorkforceScreen(){const router=useRouter();const[workers,setWorkers]=useState(seed);const toggle=(id:string)=>setWorkers(workers.map(w=>w.id===id?{...w,status:w.status==="Active"?"Needs review":"Active"}:w));return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}>
<Text style={s.eye}>ELITE BRIDGE EMPLOYER</Text><Text style={s.title}>Workforce</Text><Text style={s.sub}>See readiness, reliability and overtime exposure before you assign.</Text>
<TouchableOpacity style={s.applicationButton} onPress={()=>router.push("/applications")}><View><Text style={s.applicationEyebrow}>NEW APPLICANTS</Text><Text style={s.applicationTitle}>Review shift applications</Text><Text style={s.applicationText}>Use Elite match signals, then make the final assignment yourself.</Text></View><Text style={s.applicationArrow}>→</Text></TouchableOpacity>
<View style={s.banner}><Text style={s.bannerTitle}>AI workforce pulse</Text><Text style={s.bannerText}>2 workers need attention. Michael is within 3 hours of overtime. Emily has a credential expiring soon.</Text></View>
{workers.map(w=><View key={w.id} style={s.card}><View style={s.row}><View style={{flex:1}}><Text style={s.name}>{w.name}</Text><Text style={s.meta}>{w.role} · {w.hours} hrs this week</Text><Text style={s.meta}>{w.credentials}</Text></View><View style={s.reliability}><Text style={s.relValue}>{w.reliability}%</Text><Text style={s.relLabel}>Reliable</Text></View></View><View style={s.badges}><Text style={[s.badge,w.status==="Active"?s.good:s.warn]}>{w.status}</Text>{w.hours>=36&&<Text style={[s.badge,s.warn]}>Overtime watch</Text>}</View><TouchableOpacity style={s.button} onPress={()=>{toggle(w.id);Alert.alert("Worker status updated",`${w.name} status was changed for this workspace.`)}}><Text style={s.buttonText}>{w.status==="Active"?"Flag for review":"Mark ready"}</Text></TouchableOpacity></View>)}
</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#F7F9F8"},content:{padding:18,paddingBottom:90},eye:{fontSize:10,fontWeight:"900",letterSpacing:1.2,color:"#C58A24"},title:{fontSize:30,fontWeight:"900",color:"#101828",marginTop:4},sub:{color:"#667085",marginTop:6,marginBottom:16,lineHeight:20},applicationButton:{backgroundColor:"white",borderWidth:1,borderColor:"#C7E6D8",borderRadius:17,padding:16,marginBottom:14,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},applicationEyebrow:{color:"#C58A24",fontSize:9,fontWeight:"900",letterSpacing:1.2},applicationTitle:{color:"#0A4A35",fontSize:17,fontWeight:"900",marginTop:5},applicationText:{color:"#667085",fontSize:11,lineHeight:16,marginTop:5,maxWidth:280},applicationArrow:{color:"#0A4A35",fontSize:24,fontWeight:"900"},banner:{backgroundColor:"#0A4A35",borderRadius:17,padding:16,marginBottom:15},bannerTitle:{color:"#EBCB8B",fontSize:11,fontWeight:"900",letterSpacing:1},bannerText:{color:"white",fontSize:14,lineHeight:20,fontWeight:"700",marginTop:7},card:{backgroundColor:"white",borderWidth:1,borderColor:"#E4E7EC",borderRadius:16,padding:15,marginBottom:12},row:{flexDirection:"row",gap:12},name:{fontSize:17,fontWeight:"900",color:"#101828"},meta:{fontSize:12,color:"#667085",marginTop:4},reliability:{backgroundColor:"#ECF6F1",borderRadius:12,padding:10,alignItems:"center",minWidth:72},relValue:{fontSize:20,fontWeight:"900",color:"#087443"},relLabel:{fontSize:9,fontWeight:"800",color:"#667085"},badges:{flexDirection:"row",flexWrap:"wrap",gap:7,marginTop:12},badge:{fontSize:10,fontWeight:"900",paddingHorizontal:9,paddingVertical:6,borderRadius:999,overflow:"hidden"},good:{color:"#067647",backgroundColor:"#ECFDF3"},warn:{color:"#B54708",backgroundColor:"#FFFAEB"},button:{marginTop:12,backgroundColor:"#F2F4F7",padding:10,borderRadius:10,alignItems:"center"},buttonText:{color:"#344054",fontWeight:"900"}});
